-- ===========================================================================
-- B Cube — starting data (products, prices, media slots, site text).
-- Run AFTER 01_schema.sql. Safe to re-run: existing rows are left untouched.
--
-- Replace every __MEDIA_BASE__ below with your Storage public base URL, e.g.
--   https://YOUR-PROJECT.supabase.co/storage/v1/object/public/site-media
-- ===========================================================================

-- Products -----------------------------------------------------------------
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('premium-acrylic-photo', 'Premium Acrylic Photo', 'custom-acrylic', 'wizard', '__MEDIA_BASE__/Premium_Acrylic_Photos.png', true, 0) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('framed-acrylic-photo', 'Framed Acrylic Photo', 'custom-acrylic', 'wizard', '__MEDIA_BASE__/Framed_Acrylic_Photos.png', true, 1) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('wall-clocks', 'Wall Clocks', 'custom-acrylic', 'wizard', '__MEDIA_BASE__/Wall_Clocks.png', true, 2) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('fridge-magnet', 'Fridge Magnet', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Fridge_magnets.png', true, 3) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('name-plate', 'Name Plate', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Custom_name_plates.png', true, 4) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('keychain', 'Keychain', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Custom_Keychains.png', true, 5) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('acrylic-cutouts-decor', 'Acrylic Cutouts Décor', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Acrylic_Cutout_Decor.png', true, 6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('pillows', 'Pillows', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Custom_Pillows.png', true, 7) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('photo-albums', 'Photo Albums', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Photo_Albums.png', true, 8) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('luggage-tags', 'Luggage Tags', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Luggage_tags.png', true, 9) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('acrylic-monogram', 'Acrylic Monogram', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Acrylic_Monogram.png', true, 10) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('acrylic-desk-photo', 'Acrylic Desk Photo', 'custom-acrylic', 'custom-enquiry', '__MEDIA_BASE__/Acrylic_Desk_Photos.png', true, 11) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('hoodies', 'Hoodies', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Hoodies.png', true, 12) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('tshirt', 'Tshirt', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/T_Shirt.png', true, 13) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('laptop-bag', 'Laptop Bag', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Laptop_Bags.png', true, 14) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('water-bottle', 'Water Bottle', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Cup_Waterbottle.png', true, 15) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('pen-drive', 'Pen drive', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Pen_Drives.png', true, 16) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('cap', 'Cap', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Cap.png', true, 17) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('travel-duffle-bag', 'Travel Duffle bag', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Travel_Bag.png', true, 18) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('tote-bag', 'Tote bag', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Tote_Bag.png', true, 19) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('umbrella', 'Umbrella', 'corporate-gifting', 'bulk', '__MEDIA_BASE__/Umbrella.png', true, 20) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('candle', 'Premium Candle', 'return-gifts', 'bulk', '__MEDIA_BASE__/Premium_Candle.png', true, 21) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('container', 'Lunch Container', 'return-gifts', 'bulk', '__MEDIA_BASE__/Lunch_Container.png', true, 22) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('plant', 'Potted Plant', 'return-gifts', 'bulk', '__MEDIA_BASE__/Potted_Plant.png', true, 23) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('sweet-box', 'Sweet Box', 'return-gifts', 'bulk', '__MEDIA_BASE__/Sweet_Box.png', true, 24) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('perfume', 'Perfume', 'return-gifts', 'bulk', '__MEDIA_BASE__/Perfume.png', true, 25) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.products (slug, name, category, mode, image_url, published, sort_order) VALUES ('jute-bag', 'Jute Bag', 'return-gifts', 'bulk', '__MEDIA_BASE__/Jute_Bag.png', true, 26) ON CONFLICT (slug) DO NOTHING;

-- Prices (edit later in the admin dashboard) ---------------------------------
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('premium-acrylic-photo', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('framed-acrylic-photo', 1699, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('wall-clocks', 1899, 550, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('fridge-magnet', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('name-plate', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('keychain', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('acrylic-cutouts-decor', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('pillows', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('photo-albums', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('luggage-tags', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('acrylic-monogram', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('acrylic-desk-photo', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('hoodies', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('tshirt', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('laptop-bag', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('water-bottle', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('pen-drive', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('cap', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('travel-duffle-bag', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('tote-bag', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('umbrella', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('candle', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('container', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('plant', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('sweet-box', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('perfume', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;
INSERT INTO public.product_pricing (product_slug, base, framed, shape, size, thickness, text_price) VALUES ('jute-bag', 1299, 450, '{"rectangle":0,"rounded":100,"square":0,"circle":200,"oval":200,"arch":200,"heart":250,"triangle":200,"hexagon":250,"pentagon":250,"octagon":250,"diamond":250,"star":300}'::jsonb, '{"12 x 9":0,"16 x 12":400,"18 x 12":650,"21 x 15":1100,"30 x 20":2200}'::jsonb, '{"3 mm":0,"5 mm":300,"8 mm":700}'::jsonb, 150) ON CONFLICT (product_slug) DO NOTHING;

-- Media slots ----------------------------------------------------------------
INSERT INTO public.media (slot, kind, url, label) VALUES ('logo', 'image', '__MEDIA_BASE__/LOGO.png', 'B Cube logo') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('hero-1', 'image', '__MEDIA_BASE__/banner-1.png', 'Hero banner 1') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('hero-2', 'image', '__MEDIA_BASE__/banner-2.png', 'Hero banner 2') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('hero-3', 'image', '__MEDIA_BASE__/banner-3.png', 'Hero banner 3') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('category-1', 'image', '__MEDIA_BASE__/Cat1.png', 'Product category tile 1') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('category-2', 'image', '__MEDIA_BASE__/Cat2.png', 'Product category tile 2') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('category-3', 'image', '__MEDIA_BASE__/Cat3.png', 'Product category tile 3') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('category-bg', 'image', '__MEDIA_BASE__/Category_Bg1.png', 'Category brush background (default)') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('category-bg-hover', 'image', '__MEDIA_BASE__/Category_Bg2b.png', 'Category brush background (hover)') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('ad-1', 'image', '__MEDIA_BASE__/Advertisment_Card.png', 'Ad banner — Enriching Relationships') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('ad-2', 'image', '__MEDIA_BASE__/Advertisement_card_2.png', 'Ad banner — Know More About Our Products') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('ad-3', 'image', '__MEDIA_BASE__/Advertisement_card_3.png', 'Ad banner — Find The Perfect Gifts') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('special-1', 'image', '__MEDIA_BASE__/Corporate_gifting.png', 'Make Celebrations Special — tile 1') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('special-2', 'image', '__MEDIA_BASE__/Custom_acrylic_phots.png', 'Make Celebrations Special — tile 2') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('special-3', 'image', '__MEDIA_BASE__/Corporate_gifting.png', 'Make Celebrations Special — tile 3') ON CONFLICT (slot) DO NOTHING;
INSERT INTO public.media (slot, kind, url, label) VALUES ('special-4', 'image', '__MEDIA_BASE__/Return_Gifts.png', 'Make Celebrations Special — tile 4') ON CONFLICT (slot) DO NOTHING;

-- Editable site text ---------------------------------------------------------
INSERT INTO public.site_content (key, value) VALUES ('hero_slides', '[{"image_slot":"hero-1","tagline":"More than Decor. It''s Personal","alt":"Wall of framed family photographs","light":false},{"image_slot":"hero-2","tagline":"Show Appreciation in the right way!","alt":"Row of golden trophies and awards","light":false},{"image_slot":"hero-3","tagline":"Find the right gift for every story","alt":"Gift boxes tied with ribbons on a red backdrop","light":true}]'::jsonb) ON CONFLICT (key) DO NOTHING;
INSERT INTO public.site_content (key, value) VALUES ('testimonial_groups', '[{"id":"acrylic-photos","title":"Acrylic Photos","body":"Capture every smile with our crystal-clear acrylic prints polished, vivid, and built to last for the moments you''ll always want to revisit.","videos":["__MEDIA_BASE__/3.mp4","__MEDIA_BASE__/4.mp4","__MEDIA_BASE__/10.mp4","__MEDIA_BASE__/32.mp4","__MEDIA_BASE__/34.mp4","__MEDIA_BASE__/33.mp4"]},{"id":"acrylic-clear-photos","title":"Acrylic Clear Photos","body":"Layered transparency, perfect colour fidelity, and a tactile finish that makes every photograph feel like an heirloom.","videos":["__MEDIA_BASE__/15.mp4","__MEDIA_BASE__/16.mp4","__MEDIA_BASE__/20.mp4","__MEDIA_BASE__/29.mp4","__MEDIA_BASE__/30.mp4","__MEDIA_BASE__/31.mp4"]},{"id":"creative-gifts","title":"Creative Gifts","body":"Thoughtful, personalised gifts crafted to surprise — designed around the people and stories that matter most to you.","videos":["__MEDIA_BASE__/24.mp4","__MEDIA_BASE__/14.mp4","__MEDIA_BASE__/23.mp4","__MEDIA_BASE__/7.mp4","__MEDIA_BASE__/9.mp4","__MEDIA_BASE__/22.mp4"]},{"id":"name-decors","title":"Name Decors","body":"Make any door, desk, or doorway truly yours with a custom nameplate finished in vibrant detail.","videos":["__MEDIA_BASE__/28.mp4","__MEDIA_BASE__/6.mp4","__MEDIA_BASE__/8.mp4","__MEDIA_BASE__/12.mp4","__MEDIA_BASE__/5.mp4","__MEDIA_BASE__/35.mp4"]}]'::jsonb) ON CONFLICT (key) DO NOTHING;
INSERT INTO public.site_content (key, value) VALUES ('reviews', '[{"name":"Priya S., Chennai","quote":"I ordered a customized birthday hamper from BCUBE for my sister, and it was absolutely beautiful. The packaging, personalization, and quality were beyond my expectations. Highly recommended!"},{"name":"Karthik R., Coimbatore","quote":"BCUBE handled our corporate gifting requirements perfectly. The team was professional, delivered on time, and every gift looked premium. Our clients were genuinely impressed."},{"name":"Divya M., Madurai","quote":"Their creativity is what makes BCUBE different. They suggested unique gift ideas that I hadn''t even thought of. The final product was elegant and memorable."},{"name":"Arun Kumar V., Tiruchirappalli","quote":"Excellent customer service! They patiently accommodated all my customization requests and delivered exactly what I wanted. The quality was outstanding."},{"name":"Lakshmi N., Salem","quote":"I ordered a wedding return gift package, and every guest appreciated it. The attention to detail and finishing were exceptional. Thank you, BCUBE!"},{"name":"Suresh P., Chennai","quote":"We''ve been ordering festive gifts for our employees from BCUBE for two years now. They never disappoint. Great quality, timely delivery, and excellent support."},{"name":"Keerthana R., Erode","quote":"The personalized gifts were beautifully made and arrived in perfect condition. It made our family celebration even more special. I''ll definitely order again."},{"name":"Harish K., Tirunelveli","quote":"From placing the order to receiving the package, everything was smooth. BCUBE''s team kept me updated throughout, and the final product exceeded my expectations."},{"name":"Nandhini S., Vellore","quote":"I loved the premium look and feel of the gift box. The personalization was flawless, and the recipient absolutely loved it. BCUBE truly delivers happiness."},{"name":"Praveen Raj M., Thanjavur","quote":"If you''re looking for creative and customized gifting, BCUBE is the best choice. Their designs are unique, pricing is reasonable, and the overall experience is excellent."}]'::jsonb) ON CONFLICT (key) DO NOTHING;
