/**
 * Site media (images + videos).
 *
 * Every file lives in Supabase Storage in the public `site-media` bucket.
 * Set VITE_MEDIA_BASE_URL to the bucket's public base URL, e.g.
 *   https://<project>.supabase.co/storage/v1/object/public/site-media
 * and every asset below resolves from your own Supabase project.
 *
 * When the variable is unset the bundled Lovable CDN copies are used, so the
 * site keeps rendering before the media has been imported.
 *
 * Generated by scripts/generate-media-map.ts — do not hand-edit the map.
 */
const base = (import.meta.env?.["VITE_MEDIA_BASE_URL"] as string | undefined)?.replace(/\/$/, "");

/** Filename -> fallback URL of the originally bundled copy. */
export const mediaFallback: Record<string, string> = {
  "10.mp4": "/__l5e/assets-v1/b8192789-fa1f-4404-b79d-5f6bfdc64716/10.mp4",
  "12.mp4": "/__l5e/assets-v1/801c199a-ac2b-47b6-b124-e3cd97fb2e43/12.mp4",
  "14.mp4": "/__l5e/assets-v1/63c79011-e05d-469e-8ed6-12eb2dae2da7/14.mp4",
  "15.mp4": "/__l5e/assets-v1/2b15a716-b03a-48ab-b116-9e67efb12b5d/15.mp4",
  "16.mp4": "/__l5e/assets-v1/de9bcf7a-8151-4758-b14f-3f6d1de3f503/16.mp4",
  "2.mp4": "/__l5e/assets-v1/dd51ff22-73ce-4114-867a-852a3c201324/2.mp4",
  "20.mp4": "/__l5e/assets-v1/0c58d717-2964-4f3c-a0a7-f0a5cdafdcd1/20.mp4",
  "22.mp4": "/__l5e/assets-v1/8d69b6f2-0663-4319-938f-29aa2ae6817a/22.mp4",
  "23.mp4": "/__l5e/assets-v1/5a2d3d04-751b-450a-b853-5d155b41df8a/23.mp4",
  "24.mp4": "/__l5e/assets-v1/d744a14e-ba64-41f5-bc11-c9fe9695c060/24.mp4",
  "28.mp4": "/__l5e/assets-v1/b20313cf-fcbf-4a44-bf61-2f139799bc25/28.mp4",
  "29.mp4": "/__l5e/assets-v1/7bcb6b25-4a88-42b0-9120-1ff92f8265b7/29.mp4",
  "3-2.mp4": "/__l5e/assets-v1/5db7c9e9-cb90-4649-a615-e0c48d7d57b5/3-2.mp4",
  "3.mp4": "/__l5e/assets-v1/f5a612a3-96d5-42e6-9a8e-9e72fe193591/3.mp4",
  "30.mp4": "/__l5e/assets-v1/fc27df25-2d0c-473e-aec6-4e5f72c45476/30.mp4",
  "31.mp4": "/__l5e/assets-v1/aaaf1876-427f-4d76-83d9-197e02816bad/31.mp4",
  "32.mp4": "/__l5e/assets-v1/dcc9e317-eb4b-4a37-9556-dbcd6ff6f4b9/32.mp4",
  "33.mp4": "/__l5e/assets-v1/c5857ee7-2c81-48c9-84a1-2da196cbbd19/33.mp4",
  "34.mp4": "/__l5e/assets-v1/5e97db19-756b-4f24-a8ce-609ba80042fb/34.mp4",
  "35.mp4": "/__l5e/assets-v1/053eec9d-6225-4f3a-a99e-5402a66af7e7/35.mp4",
  "4.mp4": "/__l5e/assets-v1/93017821-82dd-4193-b7ce-6af534bb25af/4.mp4",
  "5.mp4": "/__l5e/assets-v1/5bb2424d-0531-4cb1-ad5f-7c7a81385afe/5.mp4",
  "6.mp4": "/__l5e/assets-v1/2cf88894-4c2f-429a-86ec-13716a7a1a1a/6.mp4",
  "7.mp4": "/__l5e/assets-v1/53898e5d-3916-4597-a4c4-d0612caba351/7.mp4",
  "8.mp4": "/__l5e/assets-v1/5be23893-ab10-4f54-b747-eac4a2045175/8.mp4",
  "9.mp4": "/__l5e/assets-v1/cdf1e103-dc4c-4b8c-9301-ccdac97301b3/9.mp4",
  "Acrylic_Cutout_Decor.png": "/__l5e/assets-v1/e95aa535-d153-495f-99b3-4e17b566aed6/Acrylic_Cutout_Decor.png",
  "Acrylic_Desk_Photos.png": "/__l5e/assets-v1/09a800d0-1621-4c72-84a8-6f74cd3509b2/Acrylic_Desk_Photos.png",
  "Acrylic_Monogram.png": "/__l5e/assets-v1/c35a6620-d433-45a8-9a52-a64bc7dafe6c/Acrylic_Monogram.png",
  "Advertisement_card_2.png": "/__l5e/assets-v1/22af6821-21fe-419f-bc28-e3e83a539ce0/Advertisement_card_2.png",
  "Advertisement_card_3.png": "/__l5e/assets-v1/f253cd65-6a70-4119-870e-e606ceffd6d4/Advertisement_card_3.png",
  "Advertisment_Card.png": "/__l5e/assets-v1/c84d038a-ace5-4e9c-bf6c-eb5f396961f7/Advertisment_Card.png",
  "banner-1.png": "/__l5e/assets-v1/e304b8d8-692f-4f8a-9458-992974ef62a6/banner-1.png",
  "banner-2.png": "/__l5e/assets-v1/5229e5cd-bfb2-4655-9d02-5d62b57590d0/banner-2.png",
  "banner-3.png": "/__l5e/assets-v1/29072ed0-9c89-4588-954a-41b1732dd9ac/banner-3.png",
  "Cap.png": "/__l5e/assets-v1/fb83ba03-db1d-4e42-81c4-31f0d0ed2a87/Cap.png",
  "Cat1.png": "/__l5e/assets-v1/84b345bf-d82b-4015-8cac-1fe5a9a9720b/Cat1.png",
  "Cat2.png": "/__l5e/assets-v1/84f31d71-1e1a-40f0-99bd-59aa6c7b8e16/Cat2.png",
  "Cat3.png": "/__l5e/assets-v1/3522f859-4396-4d84-80e0-611c4b07136e/Cat3.png",
  "Category_Bg1.png": "/__l5e/assets-v1/562d2f46-f707-4478-a0d4-7a613dc55423/Category_Bg1.png",
  "Category_Bg2.png": "/__l5e/assets-v1/2e61d73c-1241-4b9a-b08a-282f71741a4d/Category_Bg2.png",
  "Category_Bg2b.png": "/__l5e/assets-v1/68692d62-234f-4330-9931-fdb39faa27dc/Category_Bg2b.png",
  "Corporate_gifting.png": "/__l5e/assets-v1/5830d944-4565-4d26-adfc-cccde9811a72/Corporate_gifting.png",
  "Cup_Waterbottle.png": "/__l5e/assets-v1/5e2a7dba-2c92-4c91-924e-96ba51cdba72/Cup_Waterbottle.png",
  "Custom_acrylic_phots.png": "/__l5e/assets-v1/9ce7b135-a352-455e-a485-4046602fef7e/Custom_acrylic_phots.png",
  "Custom_Keychains.png": "/__l5e/assets-v1/b7a82af5-d347-40b2-be32-e5b57671dd65/Custom_Keychains.png",
  "Custom_name_plates.png": "/__l5e/assets-v1/b8a86209-e6b4-41b6-bf36-a648987c5258/Custom_name_plates.png",
  "Custom_Pillows.png": "/__l5e/assets-v1/d572a7eb-29b2-42a8-bef0-8a3130cfa12a/Custom_Pillows.png",
  "Framed_Acrylic_Photos.png": "/__l5e/assets-v1/4308e8a4-50d7-4c7a-9d90-082011919737/Framed_Acrylic_Photos.png",
  "Fridge_magnets.png": "/__l5e/assets-v1/1899e451-3dfe-4c39-b766-0cfb74391011/Fridge_magnets.png",
  "GildaDisplay-Regular.ttf": "/__l5e/assets-v1/b31e979c-30c9-4548-a5f7-02a6a0cc3140/GildaDisplay-Regular.ttf",
  "Gilroy-Regular.ttf": "/__l5e/assets-v1/adababcf-1092-4761-a583-bb1a11208ea6/Gilroy-Regular.ttf",
  "Hoodies.png": "/__l5e/assets-v1/ab6c0349-cee4-492f-a0bc-64f0ea46d1f8/Hoodies.png",
  "Jute_Bag.png": "/__l5e/assets-v1/88c38289-eb24-41a2-97c0-26f5abef2a4c/Jute_Bag.png",
  "Laptop_Bags.png": "/__l5e/assets-v1/48f29a0b-60a5-4dae-8cc7-2a05fda366f4/Laptop_Bags.png",
  "LOGO_1.png": "/__l5e/assets-v1/091dca16-2ea3-4ec6-93e3-573aa87ce670/LOGO_1.png",
  "LOGO.png": "/__l5e/assets-v1/6192d917-37f1-4b85-848e-65e80e35dded/LOGO.png",
  "Luggage_tags.png": "/__l5e/assets-v1/c6fd8c38-c53c-4f1f-ac11-130374638a5b/Luggage_tags.png",
  "Lunch_Container.png": "/__l5e/assets-v1/920c8f63-01a5-43bf-a52f-33ea39caf548/Lunch_Container.png",
  "Pen_Drives.png": "/__l5e/assets-v1/21b6722c-95f8-4a91-810f-c54274e5fee7/Pen_Drives.png",
  "Perfume.png": "/__l5e/assets-v1/de2cc7e9-5f42-43a9-8b3c-1948b994f880/Perfume.png",
  "Photo_Albums.png": "/__l5e/assets-v1/3f948716-3636-432e-b7d7-781b734db3a3/Photo_Albums.png",
  "Potted_Plant.png": "/__l5e/assets-v1/e3cccc14-f31a-4f70-8349-8532e8409a32/Potted_Plant.png",
  "Premiuim_Gifting.png": "/__l5e/assets-v1/c5f5934e-8e01-47cc-bf97-57706a571f95/Premiuim_Gifting.png",
  "Premium_Acrylic_Photos.png": "/__l5e/assets-v1/7ea2a6bf-2605-4d65-a2b0-74dc711c075b/Premium_Acrylic_Photos.png",
  "Premium_Candle.png": "/__l5e/assets-v1/5631dc5a-29bd-4a80-8d56-e6d695ec8519/Premium_Candle.png",
  "Return_Gifts.png": "/__l5e/assets-v1/f67598bf-2604-4285-a028-368de7734bb9/Return_Gifts.png",
  "Sweet_Box.png": "/__l5e/assets-v1/9e8a91cb-6333-4f06-add5-9304d78538cf/Sweet_Box.png",
  "T_Shirt.png": "/__l5e/assets-v1/9567cc5a-3577-4716-90b1-e4fcc4ffcc95/T_Shirt.png",
  "Tote_Bag.png": "/__l5e/assets-v1/5cb4d09f-67ab-420e-82a2-6f86654da268/Tote_Bag.png",
  "Travel_Bag.png": "/__l5e/assets-v1/2e67eca2-c18c-4cd1-8235-2a0bf0bfcb8a/Travel_Bag.png",
  "Umbrella.png": "/__l5e/assets-v1/bf8e5244-c585-4987-8e1b-709ac0dd338c/Umbrella.png",
  "Wall_Clocks.png": "/__l5e/assets-v1/7814def3-2984-416b-8541-379f07c1c285/Wall_Clocks.png",
};

/** Public URL for a media file, from Supabase Storage when configured. */
export function assetUrl(filename: string): string {
  if (base) return `${base}/${filename}`;
  return mediaFallback[filename] ?? "";
}

/** Every media filename that must exist in the `site-media` bucket. */
export const mediaFilenames = Object.keys(mediaFallback);
